-- =====================================================
-- PetPassport Expo Command Center v1
-- Public pre-show discovery, exhibitor inventory, QR/kiosk,
-- visitor leads, holds, print center, analytics, and transfer workflow.
-- Safe to run more than once.
-- =====================================================

create extension if not exists pgcrypto with schema extensions;

-- =====================================================
-- Tables
-- =====================================================

create table if not exists public.expo_events (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  slug text not null unique,
  mode text not null default 'mixed',
  status text not null default 'Draft',
  venue text not null default '',
  city text not null default '',
  region text not null default '',
  booth_number text not null default '',
  starts_at timestamptz,
  ends_at timestamptz,
  public_hours text not null default '',
  description text not null default '',
  contact_email text not null default '',
  contact_phone text not null default '',
  website_url text not null default '',
  social_handle text not null default '',
  logo_url text not null default '',
  banner_url text not null default '',
  public_expires_at timestamptz,
  is_public boolean not null default false,
  publish_inventory_at timestamptz,
  show_prices boolean not null default true,
  allow_interest boolean not null default true,
  allow_hold_requests boolean not null default true,
  kiosk_enabled boolean not null default true,
  kiosk_pin_required boolean not null default false,
  kiosk_pin_hash text,
  public_settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.expo_event_vendors (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.expo_events(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending',
  vendor_type text not null default 'Breeder',
  display_name text not null default 'PetPassport exhibitor',
  booth_number text not null default '',
  bio text not null default '',
  contact_email text not null default '',
  contact_phone text not null default '',
  website_url text not null default '',
  social_handle text not null default '',
  show_contact boolean not null default false,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (event_id, user_id)
);

create table if not exists public.expo_event_animals (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.expo_events(id) on delete cascade,
  vendor_id bigint not null references public.expo_event_vendors(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  pet_id bigint not null references public.pets(id) on delete cascade,
  listing_token text not null unique,
  listing_code text not null,
  public_snapshot jsonb not null default '{}'::jsonb,
  display_name text not null,
  species text not null default '',
  morph text not null default '',
  sex text not null default 'Unknown',
  hatch_birth_date date,
  status text not null default 'Available',
  price numeric(12,2),
  currency text not null default 'USD',
  price_label text not null default '',
  deposit_amount numeric(12,2),
  negotiable boolean not null default false,
  featured boolean not null default false,
  show_in_catalog boolean not null default true,
  booth_location text not null default '',
  public_temperament text not null default '',
  feeding_status text not null default '',
  last_fed_text text not null default '',
  weight_text text not null default '',
  care_level text not null default 'Intermediate',
  genetics text not null default '',
  parent_information text not null default '',
  included_supplies text not null default '',
  pickup_requirements text not null default '',
  expo_notes text not null default '',
  sort_order integer not null default 0,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (event_id, listing_code),
  unique (event_id, pet_id)
);

create table if not exists public.expo_leads (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.expo_events(id) on delete cascade,
  listing_id bigint references public.expo_event_animals(id) on delete set null,
  vendor_id bigint references public.expo_event_vendors(id) on delete set null,
  name text not null default '',
  email text not null default '',
  phone text not null default '',
  preferred_contact text not null default 'Email',
  interest_level text not null default 'Interested',
  timeframe text not null default '',
  hold_requested boolean not null default false,
  message text not null default '',
  consent_to_follow_up boolean not null default false,
  status text not null default 'New',
  internal_notes text not null default '',
  source text not null default 'public-expo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.expo_holds (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.expo_events(id) on delete cascade,
  listing_id bigint not null references public.expo_event_animals(id) on delete cascade,
  vendor_id bigint references public.expo_event_vendors(id) on delete set null,
  lead_id bigint references public.expo_leads(id) on delete set null,
  created_by uuid not null references auth.users(id) on delete cascade,
  visitor_name text not null default '',
  visitor_email text not null default '',
  expires_at timestamptz,
  deposit_amount numeric(12,2),
  payment_status text not null default 'Not paid',
  status text not null default 'active',
  notes text not null default '',
  released_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.expo_event_follows (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.expo_events(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  notifications_enabled boolean not null default true,
  last_viewed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (event_id, user_id)
);

create table if not exists public.expo_listing_favorites (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.expo_events(id) on delete cascade,
  listing_id bigint not null references public.expo_event_animals(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (listing_id, user_id)
);

create table if not exists public.expo_scans (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.expo_events(id) on delete cascade,
  listing_id bigint references public.expo_event_animals(id) on delete set null,
  scan_type text not null default 'event',
  referrer text,
  user_agent text,
  created_at timestamptz not null default now()
);

create table if not exists public.expo_updates (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.expo_events(id) on delete cascade,
  vendor_id bigint references public.expo_event_vendors(id) on delete set null,
  created_by uuid not null references auth.users(id) on delete cascade,
  listing_id bigint references public.expo_event_animals(id) on delete set null,
  kind text not null default 'announcement',
  title text not null,
  message text not null default '',
  is_public boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.expo_staff (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.expo_events(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'staff',
  permissions jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (event_id, user_id)
);

alter table public.expo_events add column if not exists logo_url text not null default '';
alter table public.expo_events add column if not exists banner_url text not null default '';
alter table public.expo_events add column if not exists public_expires_at timestamptz;

-- =====================================================
-- Indexes
-- =====================================================

create index if not exists expo_events_public_idx on public.expo_events (is_public, status, starts_at);
create index if not exists expo_events_owner_idx on public.expo_events (owner_id, starts_at);
create index if not exists expo_vendors_event_idx on public.expo_event_vendors (event_id, status);
create index if not exists expo_vendors_user_idx on public.expo_event_vendors (user_id, status);
create index if not exists expo_animals_event_idx on public.expo_event_animals (event_id, show_in_catalog, status, featured);
create index if not exists expo_animals_vendor_idx on public.expo_event_animals (vendor_id, status);
create index if not exists expo_animals_owner_idx on public.expo_event_animals (owner_id, pet_id);
create index if not exists expo_leads_event_idx on public.expo_leads (event_id, status, created_at desc);
create index if not exists expo_leads_vendor_idx on public.expo_leads (vendor_id, status);
create index if not exists expo_holds_event_idx on public.expo_holds (event_id, status, expires_at);
create index if not exists expo_scans_event_idx on public.expo_scans (event_id, created_at desc);
create index if not exists expo_updates_event_idx on public.expo_updates (event_id, is_public, created_at desc);

-- =====================================================
-- Shared updated_at trigger
-- =====================================================

create or replace function public.petpassport_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

DO $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'expo_events',
    'expo_event_vendors',
    'expo_event_animals',
    'expo_leads',
    'expo_holds',
    'expo_updates'
  ]
  loop
    execute format('drop trigger if exists %I on public.%I', table_name || '_updated_at', table_name);
    execute format(
      'create trigger %I before update on public.%I for each row execute function public.petpassport_set_updated_at()',
      table_name || '_updated_at',
      table_name
    );
  end loop;
end;
$$;

-- =====================================================
-- Permission helpers
-- =====================================================

create or replace function public.is_expo_owner(p_event_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.expo_events e
    where e.id = p_event_id
      and e.owner_id = auth.uid()
  );
$$;

create or replace function public.is_expo_vendor(p_event_id bigint, p_require_approved boolean default true)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.expo_event_vendors v
    where v.event_id = p_event_id
      and v.user_id = auth.uid()
      and (not p_require_approved or v.status = 'approved')
  );
$$;

create or replace function public.can_manage_expo_listing(p_listing_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.expo_event_animals a
    join public.expo_events e on e.id = a.event_id
    where a.id = p_listing_id
      and (a.owner_id = auth.uid() or e.owner_id = auth.uid())
  );
$$;


-- Prevent exhibitors from approving themselves or moving a vendor membership
-- to another user/event. Organizers still control approval status.
create or replace function public.guard_expo_vendor_security()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.event_id is distinct from old.event_id or new.user_id is distinct from old.user_id then
    raise exception 'Expo vendor identity and event cannot be changed.';
  end if;

  if new.status is distinct from old.status or new.approved_at is distinct from old.approved_at then
    if public.is_expo_owner(old.event_id) then
      return new;
    end if;

    if new.status = 'pending' and old.status in ('pending', 'rejected', 'withdrawn') then
      new.approved_at := null;
    else
      raise exception 'Only the event organizer can change exhibitor approval status.';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists expo_vendor_security_guard on public.expo_event_vendors;
create trigger expo_vendor_security_guard
before update on public.expo_event_vendors
for each row execute function public.guard_expo_vendor_security();

-- Keep listing ownership, PetPassport ownership, event, and vendor membership aligned.
create or replace function public.guard_expo_listing_relationships()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.pets p
    where p.id = new.pet_id and p.user_id = new.owner_id
  ) then
    raise exception 'The listed animal must belong to the listing owner.';
  end if;

  if not exists (
    select 1
    from public.expo_event_vendors v
    where v.id = new.vendor_id
      and v.event_id = new.event_id
      and v.user_id = new.owner_id
  ) then
    raise exception 'The listing vendor, event, and owner do not match.';
  end if;

  return new;
end;
$$;

drop trigger if exists expo_listing_relationship_guard on public.expo_event_animals;
create trigger expo_listing_relationship_guard
before insert or update on public.expo_event_animals
for each row execute function public.guard_expo_listing_relationships();

-- Keep holds connected to the correct event, listing, vendor, and lead.
create or replace function public.guard_expo_hold_relationships()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.expo_event_animals a
    where a.id = new.listing_id
      and a.event_id = new.event_id
      and (new.vendor_id is null or a.vendor_id = new.vendor_id)
  ) then
    raise exception 'The hold does not match the selected expo listing.';
  end if;

  if new.lead_id is not null and not exists (
    select 1
    from public.expo_leads l
    where l.id = new.lead_id
      and l.event_id = new.event_id
      and (l.listing_id is null or l.listing_id = new.listing_id)
      and (new.vendor_id is null or l.vendor_id is null or l.vendor_id = new.vendor_id)
  ) then
    raise exception 'The hold lead does not match the selected expo listing.';
  end if;

  return new;
end;
$$;

drop trigger if exists expo_hold_relationship_guard on public.expo_holds;
create trigger expo_hold_relationship_guard
before insert or update on public.expo_holds
for each row execute function public.guard_expo_hold_relationships();

-- =====================================================
-- Row Level Security
-- =====================================================

alter table public.expo_events enable row level security;
alter table public.expo_event_vendors enable row level security;
alter table public.expo_event_animals enable row level security;
alter table public.expo_leads enable row level security;
alter table public.expo_holds enable row level security;
alter table public.expo_event_follows enable row level security;
alter table public.expo_listing_favorites enable row level security;
alter table public.expo_scans enable row level security;
alter table public.expo_updates enable row level security;
alter table public.expo_staff enable row level security;

DO $$
declare
  r record;
begin
  for r in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in (
        'expo_events', 'expo_event_vendors', 'expo_event_animals', 'expo_leads',
        'expo_holds', 'expo_event_follows', 'expo_listing_favorites', 'expo_scans',
        'expo_updates', 'expo_staff'
      )
  loop
    execute format('drop policy if exists %I on %I.%I', r.policyname, r.schemaname, r.tablename);
  end loop;
end;
$$;

-- Events
create policy expo_events_select_members
on public.expo_events for select
to authenticated
using (
  owner_id = auth.uid()
  or public.is_expo_vendor(id, false)
  or exists (select 1 from public.expo_staff s where s.event_id = id and s.user_id = auth.uid())
);

create policy expo_events_insert_owner
on public.expo_events for insert
to authenticated
with check (owner_id = auth.uid());

create policy expo_events_update_owner
on public.expo_events for update
to authenticated
using (owner_id = auth.uid())
with check (owner_id = auth.uid());

create policy expo_events_delete_owner
on public.expo_events for delete
to authenticated
using (owner_id = auth.uid());

-- Vendors
create policy expo_vendors_select_members
on public.expo_event_vendors for select
to authenticated
using (user_id = auth.uid() or public.is_expo_owner(event_id) or public.is_expo_vendor(event_id, false));

create policy expo_vendors_request_own
on public.expo_event_vendors for insert
to authenticated
with check (
  user_id = auth.uid()
  and (
    status = 'pending'
    or public.is_expo_owner(event_id)
  )
);

create policy expo_vendors_update_self_or_owner
on public.expo_event_vendors for update
to authenticated
using (user_id = auth.uid() or public.is_expo_owner(event_id))
with check (user_id = auth.uid() or public.is_expo_owner(event_id));

create policy expo_vendors_delete_self_or_owner
on public.expo_event_vendors for delete
to authenticated
using (user_id = auth.uid() or public.is_expo_owner(event_id));

-- Event animals
create policy expo_animals_select_members
on public.expo_event_animals for select
to authenticated
using (owner_id = auth.uid() or public.is_expo_owner(event_id) or public.is_expo_vendor(event_id, false));

create policy expo_animals_insert_approved_vendor
on public.expo_event_animals for insert
to authenticated
with check (
  expo_event_animals.owner_id = auth.uid()
  and public.is_expo_vendor(expo_event_animals.event_id, true)
  and exists (
    select 1 from public.pets p
    where p.id = expo_event_animals.pet_id and p.user_id = auth.uid()
  )
  and exists (
    select 1 from public.expo_event_vendors v
    where v.id = expo_event_animals.vendor_id
      and v.event_id = expo_event_animals.event_id
      and v.user_id = auth.uid()
      and v.status = 'approved'
  )
);

create policy expo_animals_update_owner_or_organizer
on public.expo_event_animals for update
to authenticated
using (expo_event_animals.owner_id = auth.uid() or public.is_expo_owner(expo_event_animals.event_id))
with check (
  public.is_expo_owner(expo_event_animals.event_id)
  or (
    expo_event_animals.owner_id = auth.uid()
    and public.is_expo_vendor(expo_event_animals.event_id, true)
    and exists (
      select 1 from public.pets p
      where p.id = expo_event_animals.pet_id and p.user_id = auth.uid()
    )
    and exists (
      select 1 from public.expo_event_vendors v
      where v.id = expo_event_animals.vendor_id
        and v.event_id = expo_event_animals.event_id
        and v.user_id = auth.uid()
        and v.status = 'approved'
    )
  )
);

create policy expo_animals_delete_owner_or_organizer
on public.expo_event_animals for delete
to authenticated
using (owner_id = auth.uid() or public.is_expo_owner(event_id));

-- Leads
create policy expo_leads_select_managers
on public.expo_leads for select
to authenticated
using (
  public.is_expo_owner(event_id)
  or exists (
    select 1 from public.expo_event_vendors v
    where v.id = vendor_id and v.user_id = auth.uid() and v.status = 'approved'
  )
);

create policy expo_leads_update_managers
on public.expo_leads for update
to authenticated
using (
  public.is_expo_owner(event_id)
  or exists (
    select 1 from public.expo_event_vendors v
    where v.id = vendor_id and v.user_id = auth.uid() and v.status = 'approved'
  )
)
with check (
  public.is_expo_owner(event_id)
  or exists (
    select 1 from public.expo_event_vendors v
    where v.id = vendor_id and v.user_id = auth.uid() and v.status = 'approved'
  )
);

create policy expo_leads_delete_managers
on public.expo_leads for delete
to authenticated
using (public.is_expo_owner(event_id));

-- Holds
create policy expo_holds_select_managers
on public.expo_holds for select
to authenticated
using (
  public.is_expo_owner(event_id)
  or exists (
    select 1 from public.expo_event_vendors v
    where v.id = vendor_id and v.user_id = auth.uid() and v.status = 'approved'
  )
);

create policy expo_holds_insert_managers
on public.expo_holds for insert
to authenticated
with check (
  created_by = auth.uid()
  and (
    public.is_expo_owner(event_id)
    or exists (
      select 1 from public.expo_event_vendors v
      where v.id = vendor_id and v.user_id = auth.uid() and v.status = 'approved'
    )
  )
);

create policy expo_holds_update_managers
on public.expo_holds for update
to authenticated
using (
  public.is_expo_owner(event_id)
  or exists (
    select 1 from public.expo_event_vendors v
    where v.id = vendor_id and v.user_id = auth.uid() and v.status = 'approved'
  )
)
with check (
  public.is_expo_owner(event_id)
  or exists (
    select 1 from public.expo_event_vendors v
    where v.id = vendor_id and v.user_id = auth.uid() and v.status = 'approved'
  )
);

-- Follows and favorites
create policy expo_follows_own
on public.expo_event_follows for all
to authenticated
using (expo_event_follows.user_id = auth.uid())
with check (
  expo_event_follows.user_id = auth.uid()
  and exists (
    select 1 from public.expo_events e
    where e.id = expo_event_follows.event_id
      and e.is_public = true
      and e.status in ('Published', 'Live', 'Completed')
      and (e.public_expires_at is null or now() < e.public_expires_at)
  )
);

create policy expo_favorites_own
on public.expo_listing_favorites for all
to authenticated
using (expo_listing_favorites.user_id = auth.uid())
with check (
  expo_listing_favorites.user_id = auth.uid()
  and exists (
    select 1
    from public.expo_event_animals a
    join public.expo_events e on e.id = a.event_id
    where a.id = expo_listing_favorites.listing_id
      and a.event_id = expo_listing_favorites.event_id
      and a.show_in_catalog = true
      and a.status <> 'Not attending'
      and e.is_public = true
      and e.status in ('Published', 'Live', 'Completed')
      and (e.public_expires_at is null or now() < e.public_expires_at)
  )
);

-- Scans
create policy expo_scans_select_managers
on public.expo_scans for select
to authenticated
using (public.is_expo_owner(event_id) or public.is_expo_vendor(event_id, true));

-- Updates
create policy expo_updates_select_members
on public.expo_updates for select
to authenticated
using (public.is_expo_owner(event_id) or public.is_expo_vendor(event_id, false));

create policy expo_updates_insert_managers
on public.expo_updates for insert
to authenticated
with check (
  expo_updates.created_by = auth.uid()
  and (
    public.is_expo_owner(expo_updates.event_id)
    or exists (
      select 1 from public.expo_event_vendors v
      where v.id = expo_updates.vendor_id
        and v.event_id = expo_updates.event_id
        and v.user_id = auth.uid()
        and v.status = 'approved'
    )
  )
);

create policy expo_updates_update_creator_or_owner
on public.expo_updates for update
to authenticated
using (expo_updates.created_by = auth.uid() or public.is_expo_owner(expo_updates.event_id))
with check (
  public.is_expo_owner(expo_updates.event_id)
  or (
    expo_updates.created_by = auth.uid()
    and exists (
      select 1 from public.expo_event_vendors v
      where v.id = expo_updates.vendor_id
        and v.event_id = expo_updates.event_id
        and v.user_id = auth.uid()
        and v.status = 'approved'
    )
  )
);

create policy expo_updates_delete_creator_or_owner
on public.expo_updates for delete
to authenticated
using (created_by = auth.uid() or public.is_expo_owner(event_id));

-- Staff
create policy expo_staff_select_members
on public.expo_staff for select
to authenticated
using (user_id = auth.uid() or public.is_expo_owner(event_id));

create policy expo_staff_manage_owner
on public.expo_staff for all
to authenticated
using (public.is_expo_owner(event_id))
with check (public.is_expo_owner(event_id));

-- =====================================================
-- Public payload helpers
-- =====================================================

create or replace function public.expo_public_snapshot(p_snapshot jsonb)
returns jsonb
language sql
immutable
as $$
  select jsonb_build_object(
    'passport', jsonb_build_object(
      'passportId', coalesce(p_snapshot #>> '{passport,passportId}', ''),
      'name', coalesce(p_snapshot #>> '{passport,name}', ''),
      'category', coalesce(p_snapshot #>> '{passport,category}', ''),
      'animalGroup', coalesce(p_snapshot #>> '{passport,animalGroup}', ''),
      'species', coalesce(p_snapshot #>> '{passport,species}', ''),
      'morph', coalesce(p_snapshot #>> '{passport,morph}', ''),
      'sex', coalesce(p_snapshot #>> '{passport,sex}', ''),
      'dob', coalesce(p_snapshot #>> '{passport,dob}', ''),
      'ageType', coalesce(p_snapshot #>> '{passport,ageType}', ''),
      'estimatedAge', coalesce(p_snapshot #>> '{passport,estimatedAge}', ''),
      'temperament', coalesce(p_snapshot #>> '{passport,temperament}', ''),
      'photo', p_snapshot #> '{passport,photo}'
    ),
    'care', jsonb_build_object(
      'diet', coalesce(p_snapshot #>> '{care,diet}', ''),
      'foodList', coalesce(p_snapshot #> '{care,foodList}', '[]'::jsonb),
      'frequency', coalesce(p_snapshot #> '{care,frequency}', '0'::jsonb),
      'lastFed', p_snapshot #> '{care,lastFed}'
    ),
    'expo', jsonb_build_object(
      'lastFed', p_snapshot #> '{expo,lastFed}',
      'weight', coalesce(p_snapshot #>> '{expo,weight}', ''),
      'weightUnit', coalesce(p_snapshot #>> '{expo,weightUnit}', ''),
      'foods', coalesce(p_snapshot #> '{expo,foods}', '[]'::jsonb)
    )
  );
$$;

create or replace function public.get_public_expo_event(p_slug text)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_event public.expo_events%rowtype;
  v_inventory_live boolean;
  v_result jsonb;
begin
  select * into v_event
  from public.expo_events e
  where e.slug = p_slug
    and e.is_public = true
    and e.status in ('Published', 'Live', 'Completed')
    and (e.public_expires_at is null or now() < e.public_expires_at)
  limit 1;

  if v_event.id is null then
    return null;
  end if;

  v_inventory_live := v_event.publish_inventory_at is null or now() >= v_event.publish_inventory_at;

  select jsonb_build_object(
    'event', jsonb_build_object(
      'id', v_event.id,
      'name', v_event.name,
      'slug', v_event.slug,
      'mode', v_event.mode,
      'mode_label', case v_event.mode
        when 'breeder' then 'Breeder Expo'
        when 'rescue' then 'Adoption Event'
        when 'education' then 'Education / Zoo Event'
        when 'retail' then 'Retail Show'
        else 'Mixed Expo'
      end,
      'status', v_event.status,
      'venue', v_event.venue,
      'city', v_event.city,
      'region', v_event.region,
      'starts_at', v_event.starts_at,
      'ends_at', v_event.ends_at,
      'public_hours', v_event.public_hours,
      'description', v_event.description,
      'contact_email', v_event.contact_email,
      'contact_phone', v_event.contact_phone,
      'website_url', v_event.website_url,
      'social_handle', v_event.social_handle,
      'logo_url', v_event.logo_url,
      'banner_url', v_event.banner_url,
      'public_expires_at', v_event.public_expires_at,
      'show_prices', v_event.show_prices,
      'allow_interest', v_event.allow_interest,
      'allow_hold_requests', v_event.allow_hold_requests,
      'kiosk_enabled', v_event.kiosk_enabled,
      'kiosk_pin_required', v_event.kiosk_pin_required,
      'public_settings', jsonb_build_object(
        'showVendorContacts', coalesce((v_event.public_settings->>'showVendorContacts')::boolean, false),
        'featuredMessage', coalesce(v_event.public_settings->>'featuredMessage', '')
      ),
      'publish_inventory_at', v_event.publish_inventory_at,
      'is_inventory_live', v_inventory_live
    ),
    'vendors', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', v.id,
          'vendor_type', v.vendor_type,
          'display_name', v.display_name,
          'booth_number', v.booth_number,
          'bio', v.bio,
          'show_contact', v.show_contact,
          'contact_email', case when v.show_contact and coalesce((v_event.public_settings->>'showVendorContacts')::boolean, false) then v.contact_email else '' end,
          'contact_phone', case when v.show_contact and coalesce((v_event.public_settings->>'showVendorContacts')::boolean, false) then v.contact_phone else '' end,
          'website_url', case when v.show_contact and coalesce((v_event.public_settings->>'showVendorContacts')::boolean, false) then v.website_url else '' end,
          'social_handle', case when v.show_contact and coalesce((v_event.public_settings->>'showVendorContacts')::boolean, false) then v.social_handle else '' end
        ) order by v.display_name
      )
      from public.expo_event_vendors v
      where v.event_id = v_event.id and v.status = 'approved'
    ), '[]'::jsonb),
    'listings', case when v_inventory_live then coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', a.id,
          'event_id', a.event_id,
          'vendor_id', a.vendor_id,
          'listing_token', a.listing_token,
          'listing_code', a.listing_code,
          'public_snapshot', public.expo_public_snapshot(a.public_snapshot),
          'display_name', a.display_name,
          'species', a.species,
          'morph', a.morph,
          'sex', a.sex,
          'hatch_birth_date', a.hatch_birth_date,
          'status', case
            when a.status = 'On hold' and not exists (
              select 1 from public.expo_holds h
              where h.listing_id = a.id
                and h.status = 'active'
                and (h.expires_at is null or h.expires_at > now())
            ) then 'Available'
            else a.status
          end,
          'price', a.price,
          'currency', a.currency,
          'price_label', a.price_label,
          'deposit_amount', a.deposit_amount,
          'negotiable', a.negotiable,
          'featured', a.featured,
          'show_in_catalog', a.show_in_catalog,
          'booth_location', a.booth_location,
          'public_temperament', a.public_temperament,
          'feeding_status', a.feeding_status,
          'last_fed_text', a.last_fed_text,
          'weight_text', a.weight_text,
          'care_level', a.care_level,
          'genetics', a.genetics,
          'parent_information', a.parent_information,
          'included_supplies', a.included_supplies,
          'pickup_requirements', a.pickup_requirements,
          'expo_notes', a.expo_notes,
          'vendor_name', v.display_name,
          'vendor_booth', v.booth_number
        ) order by a.featured desc, a.sort_order, a.created_at
      )
      from public.expo_event_animals a
      join public.expo_event_vendors v on v.id = a.vendor_id and v.status = 'approved'
      where a.event_id = v_event.id
        and a.show_in_catalog = true
        and a.status <> 'Not attending'
    ), '[]'::jsonb) else '[]'::jsonb end,
    'updates', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', u.id,
          'kind', u.kind,
          'title', u.title,
          'message', u.message,
          'listing_id', u.listing_id,
          'vendor_name', v.display_name,
          'created_at', u.created_at
        ) order by u.created_at desc
      )
      from public.expo_updates u
      left join public.expo_event_vendors v on v.id = u.vendor_id
      where u.event_id = v_event.id and u.is_public = true
    ), '[]'::jsonb)
  ) into v_result;

  return v_result;
end;
$$;

create or replace function public.get_public_expo_events()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(jsonb_agg(q.event_payload order by q.starts_at nulls last, q.name), '[]'::jsonb)
  from (
    select
      e.starts_at,
      e.name,
      jsonb_build_object(
        'id', e.id,
        'name', e.name,
        'slug', e.slug,
        'mode', e.mode,
        'status', e.status,
        'venue', e.venue,
        'city', e.city,
        'region', e.region,
        'starts_at', e.starts_at,
        'ends_at', e.ends_at,
        'public_hours', e.public_hours,
        'description', e.description,
        'logo_url', e.logo_url,
        'banner_url', e.banner_url,
        'public_expires_at', e.public_expires_at,
        'show_prices', e.show_prices,
        'publish_inventory_at', e.publish_inventory_at,
        'is_inventory_live', (e.publish_inventory_at is null or now() >= e.publish_inventory_at),
        'public_settings', e.public_settings,
        'vendor_count', (
          select count(*) from public.expo_event_vendors v
          where v.event_id = e.id and v.status = 'approved'
        ),
        'listing_count', case when e.publish_inventory_at is null or now() >= e.publish_inventory_at then (
          select count(*) from public.expo_event_animals a
          join public.expo_event_vendors v on v.id = a.vendor_id and v.status = 'approved'
          where a.event_id = e.id and a.show_in_catalog = true and a.status <> 'Not attending'
        ) else 0 end,
        'available_count', case when e.publish_inventory_at is null or now() >= e.publish_inventory_at then (
          select count(*) from public.expo_event_animals a
          join public.expo_event_vendors v on v.id = a.vendor_id and v.status = 'approved'
          where a.event_id = e.id
            and a.show_in_catalog = true
            and (
              a.status = 'Available'
              or (
                a.status = 'On hold'
                and not exists (
                  select 1 from public.expo_holds h
                  where h.listing_id = a.id
                    and h.status = 'active'
                    and (h.expires_at is null or h.expires_at > now())
                )
              )
            )
        ) else 0 end,
        'featured_animals', case when e.publish_inventory_at is null or now() >= e.publish_inventory_at then coalesce((
          select jsonb_agg(featured.item order by featured.featured desc, featured.created_at)
          from (
            select
              a.featured,
              a.created_at,
              jsonb_build_object(
                'id', a.id,
                'display_name', a.display_name,
                'species', a.species,
                'morph', a.morph,
                'sex', a.sex,
                'price', a.price,
                'currency', a.currency,
                'price_label', a.price_label,
                'status', a.status,
                'listing_token', a.listing_token,
                'listing_code', a.listing_code,
                'vendor_name', v.display_name,
                'vendor_booth', v.booth_number,
                'booth_location', a.booth_location,
                'photo', a.public_snapshot #> '{passport,photo}'
              ) as item
            from public.expo_event_animals a
            join public.expo_event_vendors v on v.id = a.vendor_id and v.status = 'approved'
            where a.event_id = e.id
              and a.show_in_catalog = true
              and a.status <> 'Not attending'
            order by a.featured desc, a.created_at
            limit 4
          ) featured
        ), '[]'::jsonb) else '[]'::jsonb end
      ) as event_payload
    from public.expo_events e
    where e.is_public = true
      and e.status in ('Published', 'Live')
      and (e.public_expires_at is null or now() < e.public_expires_at)
  ) q;
$$;

create or replace function public.record_expo_scan(
  p_slug text,
  p_listing_token text default null,
  p_scan_type text default 'event',
  p_referrer text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event_id bigint;
  v_listing_id bigint;
begin
  select e.id into v_event_id
  from public.expo_events e
  where e.slug = p_slug
    and e.is_public = true
    and e.status in ('Published', 'Live', 'Completed')
    and (e.public_expires_at is null or now() < e.public_expires_at)
  limit 1;

  if v_event_id is null then return false; end if;

  if p_listing_token is not null then
    select a.id into v_listing_id
    from public.expo_event_animals a
    where a.event_id = v_event_id
      and a.listing_token = p_listing_token
      and a.show_in_catalog = true
      and a.status <> 'Not attending'
    limit 1;
  end if;

  insert into public.expo_scans(event_id, listing_id, scan_type, referrer, user_agent)
  values (v_event_id, v_listing_id, coalesce(nullif(p_scan_type, ''), 'event'), left(p_referrer, 1000), left(coalesce(nullif(current_setting('request.headers', true), '')::jsonb->>'user-agent', ''), 1000));

  return true;
exception when others then
  return false;
end;
$$;

create or replace function public.submit_expo_interest(
  p_slug text,
  p_listing_token text,
  p_name text,
  p_email text default '',
  p_phone text default '',
  p_preferred_contact text default 'Email',
  p_interest_level text default 'Interested',
  p_timeframe text default '',
  p_hold_requested boolean default false,
  p_message text default '',
  p_consent_to_follow_up boolean default false
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event public.expo_events%rowtype;
  v_listing public.expo_event_animals%rowtype;
  v_lead_id bigint;
begin
  select * into v_event
  from public.expo_events e
  where e.slug = p_slug
    and e.is_public = true
    and e.status in ('Published', 'Live')
    and (e.public_expires_at is null or now() < e.public_expires_at)
    and e.allow_interest = true
  limit 1;

  if v_event.id is null then
    raise exception 'This expo is not accepting interest forms.';
  end if;

  select * into v_listing
  from public.expo_event_animals a
  where a.event_id = v_event.id
    and a.listing_token = p_listing_token
    and a.show_in_catalog = true
    and a.status not in ('Sold', 'Adopted', 'Not attending')
  limit 1;

  if v_listing.id is null then
    raise exception 'This animal is no longer available for public interest.';
  end if;

  if length(trim(coalesce(p_name, ''))) < 2 then
    raise exception 'Please provide your name.';
  end if;

  if not p_consent_to_follow_up then
    raise exception 'Follow-up consent is required before sending contact details.';
  end if;

  insert into public.expo_leads (
    event_id, listing_id, vendor_id, name, email, phone, preferred_contact,
    interest_level, timeframe, hold_requested, message, consent_to_follow_up,
    status, source
  ) values (
    v_event.id,
    v_listing.id,
    v_listing.vendor_id,
    left(trim(p_name), 160),
    left(lower(trim(coalesce(p_email, ''))), 320),
    left(trim(coalesce(p_phone, '')), 80),
    left(trim(coalesce(p_preferred_contact, 'Email')), 80),
    left(trim(coalesce(p_interest_level, 'Interested')), 100),
    left(trim(coalesce(p_timeframe, '')), 120),
    case when v_event.allow_hold_requests then coalesce(p_hold_requested, false) else false end,
    left(trim(coalesce(p_message, '')), 4000),
    true,
    case when coalesce(p_hold_requested, false) and v_event.allow_hold_requests then 'Hold requested' else 'New' end,
    'public-expo'
  ) returning id into v_lead_id;

  return v_lead_id;
end;
$$;

create or replace function public.set_expo_kiosk_pin(p_event_id bigint, p_pin text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if not public.is_expo_owner(p_event_id) then
    raise exception 'Only the event organizer can set the kiosk PIN.';
  end if;

  if length(trim(coalesce(p_pin, ''))) < 4 then
    raise exception 'Use a kiosk PIN with at least four characters.';
  end if;

  update public.expo_events
  set kiosk_pin_hash = crypt(trim(p_pin), gen_salt('bf')),
      kiosk_pin_required = true,
      updated_at = now()
  where id = p_event_id;

  return true;
end;
$$;

create or replace function public.verify_expo_kiosk_pin(p_slug text, p_pin text)
returns boolean
language sql
stable
security definer
set search_path = public, extensions
as $$
  select coalesce((
    select
      case
        when e.kiosk_pin_required = false then true
        when e.kiosk_pin_hash is null then false
        else e.kiosk_pin_hash = crypt(trim(coalesce(p_pin, '')), e.kiosk_pin_hash)
      end
    from public.expo_events e
    where e.slug = p_slug and e.is_public = true
    limit 1
  ), false);
$$;


create or replace function public.release_expired_expo_holds(p_event_id bigint)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer := 0;
  v_hold record;
begin
  if not (public.is_expo_owner(p_event_id) or public.is_expo_vendor(p_event_id, true)) then
    return 0;
  end if;

  for v_hold in
    select h.id, h.listing_id, h.lead_id
    from public.expo_holds h
    where h.event_id = p_event_id
      and h.status = 'active'
      and h.expires_at is not null
      and h.expires_at <= now()
  loop
    update public.expo_holds
    set status = 'expired', released_at = now(), updated_at = now()
    where id = v_hold.id;

    update public.expo_event_animals
    set status = 'Available', updated_at = now()
    where id = v_hold.listing_id and status = 'On hold';

    if v_hold.lead_id is not null then
      update public.expo_leads
      set status = 'Contacted', updated_at = now()
      where id = v_hold.lead_id and status = 'Hold requested';
    end if;

    v_count := v_count + 1;
  end loop;

  return v_count;
end;
$$;

create or replace function public.get_expo_event_analytics(p_event_id bigint)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not (public.is_expo_owner(p_event_id) or public.is_expo_vendor(p_event_id, true)) then
    raise exception 'You do not have access to this expo analytics report.';
  end if;

  return jsonb_build_object(
    'views', (select count(*) from public.expo_scans s where s.event_id = p_event_id),
    'followers', (select count(*) from public.expo_event_follows f where f.event_id = p_event_id),
    'favorites', (select count(*) from public.expo_listing_favorites f where f.event_id = p_event_id),
    'leads', (select count(*) from public.expo_leads l where l.event_id = p_event_id),
    'holds', (select count(*) from public.expo_holds h where h.event_id = p_event_id),
    'completed', (
      select count(*) from public.expo_event_animals a
      where a.event_id = p_event_id and a.status in ('Sold', 'Adopted')
    ),
    'listing_views', coalesce((
      select jsonb_agg(jsonb_build_object(
        'listing_id', a.id,
        'display_name', a.display_name,
        'listing_code', a.listing_code,
        'count', coalesce(v.view_count, 0)
      ) order by coalesce(v.view_count, 0) desc, a.display_name)
      from public.expo_event_animals a
      left join (
        select listing_id, count(*) as view_count
        from public.expo_scans
        where event_id = p_event_id and listing_id is not null
        group by listing_id
      ) v on v.listing_id = a.id
      where a.event_id = p_event_id
    ), '[]'::jsonb),
    'listing_favorites', coalesce((
      select jsonb_agg(jsonb_build_object(
        'listing_id', a.id,
        'display_name', a.display_name,
        'listing_code', a.listing_code,
        'count', coalesce(f.favorite_count, 0)
      ) order by coalesce(f.favorite_count, 0) desc, a.display_name)
      from public.expo_event_animals a
      left join (
        select listing_id, count(*) as favorite_count
        from public.expo_listing_favorites
        where event_id = p_event_id
        group by listing_id
      ) f on f.listing_id = a.id
      where a.event_id = p_event_id
    ), '[]'::jsonb)
  );
end;
$$;

-- =====================================================
-- Grants
-- =====================================================

grant usage on schema public to anon, authenticated;

grant select, insert, update, delete on public.expo_events to authenticated;
grant select, insert, update, delete on public.expo_event_vendors to authenticated;
grant select, insert, update, delete on public.expo_event_animals to authenticated;
grant select, update, delete on public.expo_leads to authenticated;
grant select, insert, update, delete on public.expo_holds to authenticated;
grant select, insert, update, delete on public.expo_event_follows to authenticated;
grant select, insert, update, delete on public.expo_listing_favorites to authenticated;
grant select on public.expo_scans to authenticated;
grant select, insert, update, delete on public.expo_updates to authenticated;
grant select, insert, update, delete on public.expo_staff to authenticated;

grant usage, select on sequence public.expo_events_id_seq to authenticated;
grant usage, select on sequence public.expo_event_vendors_id_seq to authenticated;
grant usage, select on sequence public.expo_event_animals_id_seq to authenticated;
grant usage, select on sequence public.expo_leads_id_seq to authenticated;
grant usage, select on sequence public.expo_holds_id_seq to authenticated;
grant usage, select on sequence public.expo_event_follows_id_seq to authenticated;
grant usage, select on sequence public.expo_listing_favorites_id_seq to authenticated;
grant usage, select on sequence public.expo_scans_id_seq to authenticated;
grant usage, select on sequence public.expo_updates_id_seq to authenticated;
grant usage, select on sequence public.expo_staff_id_seq to authenticated;

revoke all on function public.get_public_expo_event(text) from public;
revoke all on function public.get_public_expo_events() from public;
revoke all on function public.record_expo_scan(text, text, text, text) from public;
revoke all on function public.submit_expo_interest(text, text, text, text, text, text, text, text, boolean, text, boolean) from public;
revoke all on function public.verify_expo_kiosk_pin(text, text) from public;
revoke all on function public.set_expo_kiosk_pin(bigint, text) from public;
revoke all on function public.get_expo_event_analytics(bigint) from public;
revoke all on function public.release_expired_expo_holds(bigint) from public;
revoke all on function public.is_expo_owner(bigint) from public;
revoke all on function public.is_expo_vendor(bigint, boolean) from public;
revoke all on function public.can_manage_expo_listing(bigint) from public;

grant execute on function public.get_public_expo_event(text) to anon, authenticated;
grant execute on function public.get_public_expo_events() to anon, authenticated;
grant execute on function public.record_expo_scan(text, text, text, text) to anon, authenticated;
grant execute on function public.submit_expo_interest(text, text, text, text, text, text, text, text, boolean, text, boolean) to anon, authenticated;
grant execute on function public.verify_expo_kiosk_pin(text, text) to anon, authenticated;
grant execute on function public.set_expo_kiosk_pin(bigint, text) to authenticated;
grant execute on function public.get_expo_event_analytics(bigint) to authenticated;
grant execute on function public.release_expired_expo_holds(bigint) to authenticated;
grant execute on function public.is_expo_owner(bigint) to authenticated;
grant execute on function public.is_expo_vendor(bigint, boolean) to authenticated;
grant execute on function public.can_manage_expo_listing(bigint) to authenticated;

-- =====================================================
-- Final validation query
-- =====================================================

select
  'Expo Command Center v1 installed' as result,
  count(*) as expo_table_count
from information_schema.tables
where table_schema = 'public'
  and table_name like 'expo_%';
